displayName=Prayer Sound Swapper
author=Aaron E
description=Customize sound effects of prayers. Swap them with your own sounds or with other prayer sound effects.
tags=Prayer,Sound,Custom,SoundSwapper,Audio
version=1.0.2
plugins=com.prayersoundswapper.PrayerSoundSwapperPlugin
build=standard
